export const categories = [
  "All", 
  "Image", 
  "Marketing & Sales", 
  "Music", 
  "Audio",
  "Text",
  "Chat",
  "Productivity",
  "Developer Tools", 
  "Data", 
  "AI Assistant", 
  "AI Detection", 
  "Legal", 
  "Website Builder", 
  "Design", 
  "Education",
  "Finance", 
  "Travel", 
  "Healthcare",    
  "Human Resources",
  "Cybersecurity",               
  "Gaming",                 
  "Robotics",
  "Customer Support",
  "Fitness",
  "Retail",
  "Fashion",
  "AR & VR",
  "Entertainment",
  "Mental Health",
  "Food & Beverage",
  "Sports & Recreation" 
]
