export const categories = [
  "All", 
  "Image Generation", 
  "Marketing & Sales", 
  "Music", 
  "Chat",
  "Productivity",
  "Developer Tools", 
  "AI Assistant", 
  "AI Detection", 
  "Legal", 
  "Website Builder", 
  "Design", 
  "AI Notetackers", 
  "Finance", 
  "Travel", 
]